'use strict';
let costingPage=document.body.dataset.workspace==='costing'?'costing':'recipes';const costingOpen=new Set();const costingDraftKey='kbr_costing_draft_v1';let costingDraft=cloud.read(costingDraftKey,{})||{};
function purchaseFactor(item,unit){const native=item.unit,n=norm(item.name),size=Number(item.measurement?.size)||0;
if(unit===native||['pc','pcs'].includes(native)&&['pc','pcs'].includes(unit))return 1;
if(['g','ml'].includes(native)&&['g','ml'].includes(unit))return 1;
if(native==='g'&&unit==='kg'||native==='ml'&&unit==='L')return 1000;
if(native==='kg'&&unit==='g'||native==='L'&&unit==='ml')return .001;
if(native==='packs'&&n==='instantcoffee'){if(unit==='g')return 1/3;if(unit==='kg')return 1000/3;}
if(native==='g'&&n==='ice'){if(unit==='sack')return 25000;if(unit==='half sack')return 12500;if(unit==='5 kg bag')return 5000;}
if(native==='pcs'&&unit==='packs'&&item.measurement?.type==='packaging'&&size>0)return size;
if(native==='pcs'&&['3ltub','13ltub'].includes(n)){const liters=n==='3ltub'?3:1.3;if(unit==='L')return 1/liters;if(['ml','g'].includes(unit))return 1/(liters*1000);}
if(native==='container'&&n==='water'){const volume=Number(item.containerVolumeMl)||0;if(volume>0){if(unit==='ml')return 1/volume;if(unit==='L')return 1000/volume;}}
return null;}
function purchaseUnits(item){const candidates=[item.unit,'g','kg','ml','L','pcs','packs','container','sack','half sack','5 kg bag'];return [...new Set(candidates)].filter(u=>purchaseFactor(item,u)!==null);}
function purchaseRecord(item,doc=state?.document){const p=doc?.purchaseCosts?.[item.id];if(p)return p;const old=doc?.prices?.[item.id+'|'+item.unit]||(['pc','pcs'].includes(item.unit)?doc?.prices?.[item.id+'|pc']:null);return old?{amount:old.quantity,unit:item.unit,price:old.price}:null;}
function baseUnitCost(item,doc=state?.document){const p=purchaseRecord(item,doc);if(!p)return null;const factor=purchaseFactor(item,p.unit),q=Number(p.amount)*factor;return factor!==null&&q>0&&Number.isFinite(q)&&Number(p.price)>=0&&Number.isFinite(Number(p.price))?(Number(p.price)+10)/q:null;}
const previousCost=cost;cost=function(c){const item=inventory.find(i=>i.id===c.itemId);if(item&&purchaseRecord(item)){const unitCost=baseUnitCost(item);return unitCost!==null&&Number.isFinite(c.stockQuantity)&&c.stockQuantity!==null?unitCost*c.stockQuantity:null;}return documentComponentCost(c,state.document);};
function documentComponentCost(c,doc){const item=inventory.find(i=>i.id===c.itemId);if(item&&purchaseRecord(item,doc)){const p=baseUnitCost(item,doc);return p!==null&&c.stockQuantity!==null&&Number.isFinite(c.stockQuantity)?p*c.stockQuantity:null;}const old=doc.prices?.[priceKey(c)];return old&&old.quantity>0&&c.quantity!==null?c.quantity*(Number(old.price)+10)/old.quantity:null;}
function repriceDocument(doc){for(const variant of doc.variants||[])for(const c of variant.components||[])c.cost=documentComponentCost(c,doc);for(const rows of Object.values(doc.addons||{}))for(const c of rows)c.cost=documentComponentCost(c,doc);for(const c of doc.directSales||[])c.cost=documentComponentCost(c,doc);const bag=doc.carryBag,item=inventory.find(i=>i.id===bag?.itemId);if(item&&purchaseRecord(item,doc)){const p=baseUnitCost(item,doc);bag.cost=p!==null&&Number.isFinite(bag.factor)?p*bag.factor:null;}else if(bag?.cost!==undefined&&!doc.prices?.[bag.itemId+'|pcs'])bag.cost=null;return doc;}
const previousSave=save;save=async function(doc){return previousSave(repriceDocument(doc));};
function renderCosting(){const doc=state?.document;if(!doc){app.innerHTML='<section>Connect to load your inventory and recipes.</section>';return;}const categories=[...new Map(inventory.map(i=>[i.categoryId||i.category||'other',i.category||'Other'])).entries()];app.innerHTML='<div class="costing-savebar"><h2>Costing</h2>'+ (role==='owner'?'<button type="button" data-savecosting>Save</button><button type="button" data-costcancel>Cancel changes</button>':'')+'<span id="costingSaveStatus" role="status"></span></div><p class="subtle">Enter the quantity bought, its unit, and total purchase price. ₱10 shipping is added per item purchase batch. Unit cost = (purchase price + ₱10) ÷ quantity bought. Prices are shared with every linked recipe.</p>'+categories.map(([id,name])=>{const items=inventory.filter(i=>(i.categoryId||i.category||'other')===id).sort((a,b)=>a.name.localeCompare(b.name));return `<details class="costing-category" data-costcategory="${esc(id)}" ${costingOpen.has(id)?'open':''}><summary><strong>${esc(name)}</strong><span>${items.length} items</span></summary><div class="purchaseForm" data-purchasecategory="${esc(id)}"><div class="purchase-head"><span>Item</span><span>Amount</span><span>Unit</span><span>Purchase price ₱</span><span>Unit cost</span></div>${items.map(i=>{const p=costingDraft[i.id]||purchaseRecord(i),units=purchaseUnits(i);return `<div class="purchase-row" data-purchaseitem="${esc(i.id)}"><strong>${esc(i.name)}</strong><label><span class="mobile-label">Amount</span><input data-amount type="number" min="0.000001" step="any" inputmode="decimal" aria-label="${esc(i.name)} purchase amount" value="${p?.amount??''}" ${role==='owner'?'':'disabled'}></label><label><span class="mobile-label">Unit</span><select data-purchaseunit aria-label="${esc(i.name)} purchase unit" ${role==='owner'?'':'disabled'}>${units.map(u=>`<option ${u===(p?.unit||i.unit)?'selected':''}>${esc(u)}</option>`).join('')}</select></label><label><span class="mobile-label">Price ₱</span><input data-purchaseprice type="number" min="0" step="any" inputmode="decimal" aria-label="${esc(i.name)} purchase price" value="${p?.price??''}" ${role==='owner'?'':'disabled'}></label><output data-unitcost>${formatUnitCost(i,baseUnitCost(i))}</output></div>`;}).join('')}</div></details>`;}).join('');app.querySelectorAll('[data-costcategory]').forEach(d=>d.addEventListener('toggle',()=>{if(d.open)costingOpen.add(d.dataset.costcategory);else costingOpen.delete(d.dataset.costcategory);}));}
function formatUnitCost(item,value){return value===null?'—':'₱'+value.toLocaleString('en-PH',{minimumFractionDigits:2,maximumFractionDigits:6})+' / '+esc(item.unit);}
function previewPurchase(row){const item=inventory.find(i=>i.id===row.dataset.purchaseitem),a=row.querySelector('[data-amount]').value,p=row.querySelector('[data-purchaseprice]').value,u=row.querySelector('[data-purchaseunit]').value,f=purchaseFactor(item,u),value=a!==''&&p!==''&&Number(a)>0&&Number(p)>=0&&f!==null?(Number(p)+10)/(Number(a)*f):null;row.querySelector('[data-unitcost]').innerHTML=formatUnitCost(item,value);}
function switchPage(page){if(editing){status('Save or cancel your changes before switching tabs.');return;}costingPage=page;document.getElementById('recipesTab').classList.toggle('selected',page==='recipes');document.getElementById('costingTab').classList.toggle('selected',page==='costing');render();}
document.getElementById('recipesTab').onclick=()=>switchPage('recipes');document.getElementById('costingTab').onclick=()=>switchPage('costing');
app.addEventListener('input',e=>{const row=e.target.closest('[data-purchaseitem]');if(!row)return;editing=true;rememberCostingRow(row);previewPurchase(row);});
app.addEventListener('change',e=>{const row=e.target.closest('[data-purchaseitem]');if(!row)return;editing=true;rememberCostingRow(row);previewPurchase(row);});
function rememberCostingRow(row){costingDraft[row.dataset.purchaseitem]={amount:row.querySelector('[data-amount]').value,unit:row.querySelector('[data-purchaseunit]').value,price:row.querySelector('[data-purchaseprice]').value};localStorage.setItem(costingDraftKey,JSON.stringify(costingDraft));}
function costingMessage(text){status(text);const el=document.getElementById('costingSaveStatus');if(el)el.textContent=text;}
async function saveAllCosting(){const button=app.querySelector('[data-savecosting]');try{if(role!=='owner')throw Error('Owner login required.');if(busy)throw Error('Sync is finishing. Please press Save again in a moment.');if(cloud.read(pendingKey)){await flush();if(cloud.read(pendingKey))throw Error(note.textContent);}
const doc=copy(state.document);doc.purchaseCosts={...(doc.purchaseCosts||{})};
for(const [id,p] of Object.entries(costingDraft)){const item=inventory.find(i=>i.id===id);if(!item)throw Error('An edited inventory item was removed. Cancel changes and refresh.');const a=p.amount,price=p.price,u=p.unit;if(a===''&&price===''){delete doc.purchaseCosts[id];for(const k of Object.keys(doc.prices||{}))if(k.startsWith(id+'|'))delete doc.prices[k];continue;}
if(a===''||price===''||!(Number(a)>0)||!Number.isFinite(Number(a))||Number(price)<0||!Number.isFinite(Number(price))||purchaseFactor(item,u)===null){const row=[...app.querySelectorAll('[data-purchaseitem]')].find(r=>r.dataset.purchaseitem===id);if(row){const detail=row.closest('details');if(detail)detail.open=true;row.classList.add('costing-invalid');row.scrollIntoView({block:'center'});row.querySelector(a===''||!(Number(a)>0)?'[data-amount]':'[data-purchaseprice]').focus();}throw Error(item.name+': enter both a positive amount and a price (zero is allowed).');}
doc.purchaseCosts[id]={amount:Number(a),unit:u,price:Number(price)};}
if(!Object.keys(costingDraft).length){costingMessage(cloud.read(pendingKey)?note.textContent:'No unsaved costing changes.');return;}
if(button)button.disabled=true;const scroll=window.scrollY;editing=false;await save(doc);costingDraft={};localStorage.removeItem(costingDraftKey);render();window.scrollTo(0,scroll);costingMessage(cloud.read(pendingKey)?note.textContent:'All costing changes saved and synced.');
}catch(e){if(Object.keys(costingDraft).length)editing=true;costingMessage(e.message);}finally{const b=app.querySelector('[data-savecosting]');if(b)b.disabled=false;}}
app.addEventListener('click',e=>{if(e.target.closest('[data-savecosting]')){saveAllCosting();return;}if(!e.target.closest('[data-costcancel]'))return;costingDraft={};localStorage.removeItem(costingDraftKey);editing=false;render();costingMessage('Unsaved costing changes cancelled.');});
