(()=>{'use strict';
const HOME='https://russelljohnramosmicumao-arch.github.io/KapeBarrioHomeScreen/';
const svg=(paths)=>'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">'+paths+'</svg>';
const header=document.querySelector('header'),tools=document.createElement('div');tools.className='kbr-page-tools';
const home=document.createElement('a');home.href=HOME;home.target='_top';home.className='kbr-tool';home.title='Go to home screen';home.setAttribute('aria-label','Go to home screen');home.innerHTML=svg('<path d="m3 10 9-7 9 7M5 9v12h14V9M9 21v-8h6v8"/>');tools.append(home);
const button=document.getElementById('updateBtn')||document.getElementById('recipeUpdate')||document.createElement('button');button.type='button';button.classList.add('kbr-tool');button.title='Check for updates';button.setAttribute('aria-label','Check for updates');button.innerHTML=svg('<path d="M20 7v5h-5M4 17v-5h5M6 7a7 7 0 0 1 12-1l2 6M4 12l2 6a7 7 0 0 0 12-1"/>');
const dot=document.createElement('span');dot.className='kbr-update-dot';dot.hidden=true;dot.setAttribute('aria-hidden','true');button.append(dot);
if(button.parentNode)button.parentNode.insertBefore(home,button);else{tools.append(button);const host=header?.querySelector('.top-actions,.manager-tools,.barista-actions,nav')||header;if(host)host.append(tools);else{tools.classList.add('kbr-floating-tools');document.body.append(tools);}}
const note=document.createElement('span');note.className='kbr-update-note';note.setAttribute('role','status');button.insertAdjacentElement('afterend',note);
const staffActions=document.querySelector('#baristaDrawer .barista-actions');if(staffActions){const mirrorHome=home.cloneNode(true),mirrorButton=button.cloneNode(true),mirrorNote=note.cloneNode(true);mirrorButton.removeAttribute('id');mirrorButton.onclick=()=>button.click();staffActions.append(mirrorHome,mirrorButton,mirrorNote);const mirror=()=>{mirrorButton.disabled=button.disabled;mirrorButton.title=button.title;mirrorButton.setAttribute('aria-label',button.getAttribute('aria-label'));mirrorButton.querySelector('.kbr-update-dot').hidden=dot.hidden;mirrorNote.textContent=note.textContent;};const observer=new MutationObserver(mirror);observer.observe(button,{attributes:true,subtree:true});observer.observe(note,{childList:true,subtree:true,characterData:true});mirror();}
if(!('serviceWorker'in navigator)){button.disabled=true;note.textContent='Updates unavailable in this browser.';return;}
let registration,requested=false,reloading=false,checking=false,stale=false,controlled=!!navigator.serviceWorker.controller;
function blocked(){const arrays=['kbr_inventory_count_queue_v2','kbr_inventory_count_draft_v2'];const objects=['kbr_inventory_check_draft_v1','kbr_costing_draft_v1'];try{if(arrays.some(k=>JSON.parse(localStorage.getItem(k)||'[]').length)||objects.some(k=>Object.keys(JSON.parse(localStorage.getItem(k)||'{}')).length)||['kbr_order_write_v1','kbr_order_draft_v1','kbr_menu_write_v1','kbr_drawer_action_v1','kbr_excel_recipe_pending_v1'].some(k=>localStorage.getItem(k))){note.textContent='Sync saved changes before updating.';return true;}}catch{note.textContent='Review saved changes before updating.';return true;}
if(typeof cart!=='undefined'&&cart.length||typeof editing!=='undefined'&&editing||document.querySelector('dialog[open],#cloudScreen')||[...document.querySelectorAll('input[type="password"]')].some(i=>i.value)){note.textContent='Finish the current edit before updating.';return true;}return false;}
function show(){dot.hidden=!(registration?.waiting||stale);button.title=dot.hidden?'Check for updates':'Update available';button.setAttribute('aria-label',button.title);if(requested&&registration?.waiting){if(blocked()){requested=false;return;}reloading=true;registration.waiting.postMessage({type:'SKIP_WAITING'});note.textContent='Updating…';}}
async function check(){if(checking||!registration)return;checking=true;try{await registration.update();show();if(requested&&!registration.waiting&&!registration.installing){requested=false;location.reload();}}catch{requested=false;note.textContent='Connect to the internet to update.';}finally{checking=false;}}
button.onclick=()=>{if(blocked())return;if(!registration){note.textContent='Update check is starting…';return;}requested=true;note.textContent='Checking…';if(registration.waiting)show();else check();};
navigator.serviceWorker.addEventListener('controllerchange',()=>{if(reloading){reloading=false;location.reload();}else if(!controlled){controlled=true;}else{stale=true;show();note.textContent='Refresh to load the updated page.';}});
navigator.serviceWorker.register(document.body.dataset.updateWorker||'sw.js',{updateViaCache:'none'}).then(r=>{registration=r;show();r.addEventListener('updatefound',()=>{const w=r.installing;w?.addEventListener('statechange',()=>{if(w.state==='installed')setTimeout(show,0);if(w.state==='redundant'){requested=false;note.textContent='Update did not finish. Try again.';}});});check();}).catch(()=>{button.disabled=true;note.textContent='Update checks unavailable.';});
setInterval(()=>{if(!document.hidden)check();},60000);window.addEventListener('focus',check);window.addEventListener('online',check);
})();
