'use strict';
let stockItems=[],shopMenu=[],recipeBindings={},recipePrices={};
const norm=x=>String(x??'').toLowerCase().replace(/[^a-z0-9]/g,'');
const itemKey=(name,unit)=>norm(name)+'|'+unit;
function stockName(name){const aliases={sweetener:'Sweetener Syrup',coffeeespressosyrup:'Coffee Syrup',coffeeground:'Coffee Beans',espressoshot:'Coffee Beans',taromilktea:'Taro Powder',matchaceremonialpowder:'Matcha Powder (Premium)',bobapearlcooked:'Bobba Pearl',boobapearls:'Bobba Pearl',bobastraw:'Bobba Straws',thinstraw:'Thin Straws',flatstraw:'Thin Straws',flatlid:'Flat Lids',domelid:'Dome Lids',singlebag:'Single Bags',carrybag:'Single Bags',sprite:'Sprite Soda',blueberryjam:'Blueberry Jam',avocadomilkshakepoweder:'Avocado Powder',wintermelon:'Winter Melon Powder',cookiesandcream:'Cookies and Cream Powder',whitebunnymilktea:'White Bunny Powder',okinawa:'Okinawa Powder',blackforestpowder:'Black Forest Powder',icecreamvanilla:'3 L Tub'};return aliases[norm(name)]||name;}
function bindingFor(name,unit){const key=itemKey(name,unit);if(norm(name)==='carrybag'){const bags=stockItems.filter(i=>norm(i.name)==='singlebags'&&['pc','pcs'].includes(norm(i.unit)));return bags.length===1?{itemId:bags[0].id,factor:1}:{itemId:'',factor:null};}if(recipeBindings[key]&&!(norm(name)==='carrybag'&&(!recipeBindings[key].itemId||recipeBindings[key].factor==null)))return recipeBindings[key];const candidates=stockItems.filter(i=>norm(i.name)===norm(stockName(name)));const compatible=candidates.filter(i=>['g','ml'].includes(unit)&&['g','ml'].includes(norm(i.unit))||unit==='pc'&&['pc','pcs'].includes(norm(i.unit)));const matches=compatible.length?compatible:candidates;if(matches.length!==1)return {itemId:'',factor:null};const i=matches[0],u=norm(i.unit);let factor=null;if(['g','ml'].includes(unit)&&['g','ml'].includes(u)||unit==='pc'&&['pc','pcs'].includes(u))factor=1;if(norm(name)==='icecreamvanilla'&&['pcs','pc'].includes(u))factor=1/3000;return {itemId:i.id,factor};}
function expandRows(rows,selectedSize){return rows.flatMap(r=>{const n=norm(r.name),q=r.quantity;if(n==='milkmade')return [{name:'Milk essence',quantity:q===null?null:q*.1,unit:'g'},{name:'Water',quantity:q,unit:'ml'}];if(n==='espressoshot')return [{name:'Coffee ground',quantity:q===null?null:q*18,unit:'g'}];if(n==='chuckie'||n==='dutchmill'){const brand=n==='chuckie'?'Chuckie':'Dutchmill';return selectedSize==='12'?[{name:brand+' Small',quantity:1,unit:'pc'}]:selectedSize==='16'?[{name:brand+' Big',quantity:1,unit:'pc'}]:[{name:brand+' Small',quantity:1,unit:'pc'},{name:brand+' Big',quantity:1,unit:'pc'}];}let quantity=q,unit=r.unit;if(unit==='pump'){quantity=q===null?null:q*10;unit='ml';}if(unit==='scoop'&&/icecream/.test(n)){quantity=q===null?null:q*40;unit='g';}if(unit==='tbsp'){quantity=q===null?null:q*13;unit='g';}if(unit==='sachet'&&/coffee/.test(n)){quantity=q===null?null:q*5;unit='g';}return [{...r,quantity,unit}];});}
function packagingFor(d,s){const milk=d.category==='Milk Tea Series'||/milk\s*tea/i.test(d.name),frappe=d.category==='Frappe & Smoothies'||d.category==='Floats'||/frappe|frappuccino|frapmacchiato/i.test(d.name);return [{name:s+' oz cup',quantity:1,unit:'pc'},{name:milk?'Boba straw':'Thin straw',quantity:1,unit:'pc'},{name:frappe?'Dome lid':'Flat lid',quantity:1,unit:'pc'},...(milk?[{name:'Parchment paper',quantity:1,unit:'pc'}]:[]),{name:'Single milk tea plastic',quantity:1,unit:'pc'}];}
function inContext(d,s,t,ice,fn){const prior={size,type,withIce};try{size=s;type=t;withIce=ice;return fn();}finally{size=prior.size;type=prior.type;withIce=prior.withIce;}}
function ingredientsFor(d,s,t,ice){return inContext(d,s,t,ice,()=>{const v=variant(d);return v?getRows(d,'ingredients',v,packagingFor(d,s)):null;});}
function componentsFor(d,s,t,ice){return inContext(d,s,t,ice,()=>{const v=variant(d);if(!v)return null;if(d.blankRecipe&&!getRows(d,'ingredients',v,packagingFor(d,s)).length)return null;const rows=[...getRows(d,'ingredients',v,packagingFor(d,s)),...getRows(d,'packaging',v,packagingFor(d,s))];return expandRows(rows,s).map(r=>{const native=stockItems.find(i=>i.id===r.itemId);const same=(u,v)=>u===v||['pc','pcs'].includes(u)&&['pc','pcs'].includes(v);const convert=native?(same(r.unit,native.unit)?1:r.unit==='g'&&native.unit==='kg'||r.unit==='ml'&&native.unit==='L'?0.001:r.unit==='kg'&&native.unit==='g'||r.unit==='L'&&native.unit==='ml'?1000:null):null;const fallback=bindingFor(r.name,r.unit);const b=r.itemId?{itemId:r.itemId,factor:convert??(fallback.itemId===r.itemId?fallback.factor:null)}:fallback;const price=recipePrices[itemKey(r.name,r.unit)];return {name:r.name,quantity:r.quantity,unit:r.unit,cost:price&&r.quantity!==null?r.quantity*price.price/price.quantity:null,itemId:b.itemId,stockQuantity:r.quantity===null||b.factor===null?null:r.quantity*b.factor};});});}
function costRows(rows,s){let sum=0,missing=[];for(const r of expandRows(rows,s)){const price=recipePrices[itemKey(r.name,r.unit)];if(!price||r.quantity===null){missing.push(r.name);continue;}sum+=r.quantity*price.price/price.quantity;}return {total:sum,missing};}
function recipeCostFor(d,s){if(priceFor(d,s)===null)return '—';return inContext(d,s,type,withIce,()=>{const v=variant(d);if(!v||d.blankRecipe&&!getRows(d,'ingredients',v,packagingFor(d,s)).length)return 'Recipe needed';const rows=[...getRows(d,'ingredients',v,packagingFor(d,s)),...getRows(d,'packaging',v,packagingFor(d,s))];const result=costRows(rows,s);return result.missing.length?'Prices needed':peso(result.total);});}
function compiledRecipes(){const variants=[];const menu=shopMenu.length?shopMenu:DRINKS;for(const product of menu){const name=String(product.name);if(['crackingmatcha','nutellamatcha','mangomatcha'].includes(norm(name))||product.food)continue;const choices=DRINKS.filter(d=>!d.discontinued&&norm(d.name)===norm(name)||product.productId&&d.productId===product.productId);const d=choices.find(d=>norm(d.category)===norm(product.category))||choices[0];if(!d)continue;for(const t of ['regular','premium']){const sizes=t==='premium'?product.premiumSizes:product.sizes;if(t==='premium'&&!product.premium)continue;for(const label of sizes||[]){const s=String(label).match(/12|16|22/)?.[0];if(!s||isFrappe(d)&&s==='12')continue;const ice=/w\/ ice|with ice/i.test(label)||s==='22'&&d.category==='Frappe & Smoothies';const components=componentsFor(d,s,t,ice);if(components)variants.push({productId:product.productId||d.productId,name:product.name,category:product.category,type:t,size:label,components});}}}return variants;}
function recipeDocument(){return {version:1,catalogReset:'ordering-menu-v1',rows:savedRows,prices:recipePrices,bindings:recipeBindings,variants:compiledRecipes(),carryBag:{...bindingFor('Carry bag','pc'),quantity:1,cost:recipePrices[itemKey('Carry bag','pc')]?recipePrices[itemKey('Carry bag','pc')].price/recipePrices[itemKey('Carry bag','pc')].quantity:null},addons:{iceCream:expandRows([{name:'Ice cream (vanilla)',quantity:40,unit:'g'}],'16').map(r=>{const b=bindingFor(r.name,r.unit);const price=recipePrices[itemKey(r.name,r.unit)];return {...r,cost:price?r.quantity*price.price/price.quantity:null,itemId:b.itemId,stockQuantity:b.factor===null?null:r.quantity*b.factor};}),pearl:expandRows([{name:'Boba pearl cooked',quantity:50,unit:'g'}],'16').map(r=>{const b=bindingFor(r.name,r.unit);const price=recipePrices[itemKey(r.name,r.unit)];return {...r,cost:price?r.quantity*price.price/price.quantity:null,itemId:b.itemId,stockQuantity:b.factor===null?null:r.quantity*b.factor};})}};}
function allUsageRows(){return stockItems.map(i=>({name:i.name,itemId:i.id,unit:['pc','pcs'].includes(i.unit)?'pc':i.unit,quantity:1})).sort((a,b)=>a.name.localeCompare(b.name));}
